import type { Metadata } from "next";
import Link from "next/link";
import { Icon } from "@/components/Icon";

export const metadata: Metadata = {
  title: "Dobrna",
  description: "A Persian bingo game in development. Virtual points only, no wagering.",
};

/**
 * The build order, stated plainly.
 *
 * A "coming soon" page with no detail is indistinguishable from vapourware,
 * and this project's whole argument is that it says checkable things. So it
 * names the stages, marks the one in progress, and gives no launch date —
 * a date invented to look confident is the fastest way to lose the credit
 * the rest of the site is trying to earn.
 */
const STAGES = [
  {
    title: "Game engine",
    body: "Card generation to Dobrna rules, cryptographically random draws, and winner detection — all server-side, with the client only displaying what the server decided.",
    state: "building" as const,
  },
  {
    title: "Rooms and real time",
    body: "Public and private rooms, a lobby, live draws pushed to every player at once, and reconnection that does not cost you your card.",
    state: "next" as const,
  },
  {
    title: "Accounts and points",
    body: "Sign in with the same wallet you use here. Virtual points, game history, and win statistics.",
    state: "next" as const,
  },
  {
    title: "Persian interface",
    body: "Right-to-left throughout, in the same dark and gold design as the rest of the site.",
    state: "next" as const,
  },
];

const RULES = [
  {
    n: "01",
    title: "Ninety numbers, one card each",
    body: "Numbers run 1 to 90. Every card is generated by the server to standard Dobrna structure — three rows of nine columns, five numbers per row, each column drawing from its own decade.",
  },
  {
    n: "02",
    title: "Three ways to win",
    body: "One completed row, two completed rows, then the full card. Each is claimed separately, and each can only be claimed once per game.",
  },
  {
    n: "03",
    title: "The server draws, not your browser",
    body: "Numbers come from the server using a cryptographically secure random source, and no number is ever drawn twice in a game. Nothing about the outcome can be changed from the client.",
  },
  {
    n: "04",
    title: "Every game is recorded",
    body: "Each game gets an id, and the full draw order and every claim are stored. A disputed result can be replayed rather than argued about.",
  },
];

export default function DobrnaPage() {
  return (
    <div className="container-page space-y-14 py-10 sm:space-y-20 sm:py-14">
      {/* ---------------------------------------------------------- hero */}
      <section>
        <p className="eyebrow">
          <span className="h-1.5 w-1.5 animate-pulse rounded-full bg-warn-400 shadow-[0_0_10px_2px_rgba(245,178,66,.6)]" />
          In development
        </p>
        <h1 className="h-display mt-5">
          <span className="text-gold-gradient">Dobrna</span> — Persian bingo,
          <br className="hidden sm:block" /> built the same way as the rest of this.
        </h1>
        <p className="mt-5 max-w-2xl text-lg leading-relaxed text-graphite-300">
          A multiplayer game of دبرنا, played with virtual points. It is not finished and it is not
          playable yet — this page exists so you can see what is being built rather than find it
          appear one day with no explanation.
        </p>

        <div className="glass mt-7 flex max-w-2xl items-start gap-3 p-5">
          <Icon name="info" className="mt-0.5 h-5 w-5 shrink-0 text-warn-400" />
          <p className="text-sm leading-relaxed text-graphite-300">
            <span className="font-semibold text-white">Virtual points only.</span> No deposit buys
            an entry, no prize pays out in USDT, and none of it touches the staking contract or your
            balance. It is a game, kept deliberately separate from the money.
          </p>
        </div>
      </section>

      {/* -------------------------------------------------------- stages */}
      <section>
        <h2 className="h-section">Where it is</h2>
        <div className="mt-8 grid gap-4 sm:grid-cols-2">
          {STAGES.map((s, i) => (
            <div
              key={s.title}
              className={`glass p-6 ${s.state === "building" ? "glass-gold" : ""}`}
            >
              <div className="flex items-start gap-4">
                <span
                  className={`grid h-8 w-8 shrink-0 place-items-center rounded-full font-display text-sm font-bold ${
                    s.state === "building"
                      ? "bg-gold-sheen text-onGold shadow-gold"
                      : "border border-white/10 bg-white/[.04] text-graphite-400"
                  }`}
                >
                  {i + 1}
                </span>
                <div className="min-w-0">
                  <div className="flex flex-wrap items-center gap-2.5">
                    <h3 className="font-display font-semibold text-white">{s.title}</h3>
                    <span
                      className={`rounded-full px-2.5 py-0.5 text-[11px] font-medium ${
                        s.state === "building"
                          ? "bg-gold-400/15 text-gold-300"
                          : "bg-white/[.05] text-graphite-400"
                      }`}
                    >
                      {s.state === "building" ? "in progress" : "not started"}
                    </span>
                  </div>
                  <p className="mt-2 text-sm leading-relaxed text-graphite-300">{s.body}</p>
                </div>
              </div>
            </div>
          ))}
        </div>
        <p className="mt-5 text-xs leading-relaxed text-graphite-500">
          No launch date, deliberately. A date invented to sound confident is the fastest way to
          lose the credit the rest of this site is trying to earn. It ships when the winner
          detection has tests that pass.
        </p>
      </section>

      {/* --------------------------------------------------------- rules */}
      <section>
        <h2 className="h-section">How it will work</h2>
        <div className="mt-8 grid gap-4 lg:grid-cols-2">
          {RULES.map((r) => (
            <div key={r.n} className="glass p-6">
              <div className="flex items-start gap-4">
                <span className="font-display text-2xl font-bold text-graphite-700">{r.n}</span>
                <div className="min-w-0">
                  <h3 className="font-display font-semibold text-white">{r.title}</h3>
                  <p className="mt-2 text-sm leading-relaxed text-graphite-300">{r.body}</p>
                </div>
              </div>
            </div>
          ))}
        </div>
      </section>

      {/* ------------------------------------------------------- closing */}
      <section className="glass glass-gold p-7 text-center sm:p-10">
        <h2 className="h-section mx-auto max-w-2xl">It gets announced in one place</h2>
        <p className="mx-auto mt-4 max-w-xl text-[15px] leading-relaxed text-graphite-300">
          When the first room opens, it goes on the channel. There is nothing to sign up for here
          and nothing to pre-purchase — if anyone offers you either, it is not us.
        </p>
        <div className="mt-7 flex flex-wrap items-center justify-center gap-3">
          <a
            href="https://t.me/arbhub_site"
            target="_blank"
            rel="noreferrer"
            className="btn-primary"
          >
            Follow the channel
            <Icon name="external" className="h-4 w-4" />
          </a>
          <Link href="/dashboard" className="btn-secondary">
            Back to the platform
          </Link>
        </div>
      </section>
    </div>
  );
}
